version: '3'
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 1000:1000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - ./.postgres.env
    ports:
      - 5431:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
