version: '3'
services:
  backend:
    networks:
      - nest-network

    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 1000:1000
    depends_on:
      - db

  db:
    networks:
      - nest-network
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=auto-service

    ports:
      - 5431:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  nest-network:
    driver: bridge
